[[recipe]]
name = "_default"
shown = true
position = 0
color = "#7ec8ff"

[[recipe]]
name = "build"
shown = true
position = 1
color = "#7ec8ff"

[[recipe]]
name = "clean"
shown = true
position = 2
color = "#7ec8ff"

[[recipe]]
name = "install"
shown = true
position = 3
color = "#7ec8ff"

[[recipe]]
name = "run"
shown = true
position = 4
color = "#7ec8ff"

[[recipe]]
name = "test"
shown = true
position = 5
color = "#7ec8ff"

[[recipe]]
name = "uninstall"
shown = true
position = 6
color = "#7ec8ff"
